# Generated by Django 3.1.3 on 2020-12-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinedemo', '0002_highlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
            ],
        ),
    ]
